# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:/Users/Asus/PycharmProjects/BMP180Nokia5110LCD/BMP180Nokia5110.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(997, 582)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.pbStart = QtWidgets.QPushButton(self.centralwidget)
        self.pbStart.setGeometry(QtCore.QRect(60, 270, 151, 41))
        self.pbStart.setObjectName("pbStart")
        self.pbStop = QtWidgets.QPushButton(self.centralwidget)
        self.pbStop.setGeometry(QtCore.QRect(60, 340, 151, 41))
        self.pbStop.setObjectName("pbStop")
        self.pbExit = QtWidgets.QPushButton(self.centralwidget)
        self.pbExit.setGeometry(QtCore.QRect(60, 410, 151, 41))
        self.pbExit.setObjectName("pbExit")
        self.tblDatabase = QtWidgets.QTableWidget(self.centralwidget)
        self.tblDatabase.setGeometry(QtCore.QRect(520, 50, 431, 421))
        self.tblDatabase.setRowCount(2)
        self.tblDatabase.setColumnCount(5)
        self.tblDatabase.setObjectName("tblDatabase")
        self.lcdTemp = QtWidgets.QLCDNumber(self.centralwidget)
        self.lcdTemp.setGeometry(QtCore.QRect(60, 60, 111, 81))
        self.lcdTemp.setObjectName("lcdTemp")
        self.lcdPressure = QtWidgets.QLCDNumber(self.centralwidget)
        self.lcdPressure.setGeometry(QtCore.QRect(200, 60, 111, 81))
        self.lcdPressure.setObjectName("lcdPressure")
        self.lcdAltitude = QtWidgets.QLCDNumber(self.centralwidget)
        self.lcdAltitude.setGeometry(QtCore.QRect(350, 60, 101, 81))
        self.lcdAltitude.setObjectName("lcdAltitude")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(60, 20, 81, 21))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(200, 20, 81, 21))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(350, 20, 81, 21))
        self.label_3.setObjectName("label_3")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 997, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "BMP180 & Nokia5110 LCD"))
        self.pbStart.setText(_translate("MainWindow", "START"))
        self.pbStop.setText(_translate("MainWindow", "STOP"))
        self.pbExit.setText(_translate("MainWindow", "EXIT"))
        self.label.setText(_translate("MainWindow", "Temperature"))
        self.label_2.setText(_translate("MainWindow", "Pressure"))
        self.label_3.setText(_translate("MainWindow", "Altitude"))
